# Generated by Django 2.1.7 on 2019-03-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_auto_20190316_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='products'),
        ),
    ]
