# Generated by Django 2.1.7 on 2019-03-22 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0006_auto_20190322_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('product_type', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='priduct_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default='Syropy', on_delete=django.db.models.deletion.CASCADE, to='appone.ProductType'),
            preserve_default=False,
        ),
    ]
